image: node:18

stages:
  - test

variables:
  TEST_ENV: dev

api_tests:
  stage: test
  script:
    - npm install
    - npm run test:$TEST_ENV
  artifacts:
    paths:
      - reports/
    expire_in: 1 week
  only:
    - main
    - merge_requests
